[workspace]
resolver = "2"
members = [
    "led-wall",
    "rust-rpi-rgb-led-matrix/rpi-led-matrix",
    "rust-rpi-rgb-led-matrix/rpi-led-matrix-sys",
]

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
opt-level = 3
